#!/bin/bash

# This script converts log files produced by CVS into Perl DataDumper
# files that can be easily loaded by the buildfarm web interface.

#cd $HOME/master || exit 1

(

./svnlog.pl svn://svnanon.samba.org/samba trunk 60 samba cache/history.samba
./svnlog.pl svn://svnanon.samba.org/samba branches/SAMBA_2_2 60 samba_2_2 cache/history.samba_2_2
./svnlog.pl svn://svnanon.samba.org/samba branches/SAMBA_2_2_RELEASE 60 samba_2_2_release cache/history.samba_2_2_release
./svnlog.pl svn://svnanon.samba.org/samba branches/SAMBA_3_2 60 samba_3_2 cache/history.samba_3_2
./svnlog.pl svn://svnanon.samba.org/samba branches/SAMBA_3_0_RELEASE 60 samba_3_0_release cache/history.samba_3_0_release
./svnlog.pl svn://svnanon.samba.org/samba-docs trunk 60 samba-docs cache/history.samba-docs
./svnlog.pl svn://svnanon.samba.org/samba branches/SAMBA_4_0 60 samba4 cache/history.samba4
./svnlog.pl svn://svnanon.samba.org/samba-web trunk 60 samba-web cache/history.samba-web
./svnlog.pl svn://svnanon.samba.org/lorikeet trunk 60 lorikeet cache/history.lorikeet
./svnlog.pl svn://svnanon.samba.org/samba branches/SAMBA_4_0/source/lib/talloc 60 talloc cache/history.talloc
./svnlog.pl svn://svnanon.samba.org/samba branches/SAMBA_4_0/source/lib/tdb 60 tdb cache/history.tdb
./svnlog.pl svn://svnanon.samba.org/samba branches/SAMBA_4_0/source/lib/ldb 60 ldb cache/history.ldb
./svnlog.pl svn://svnanon.samba.org/samba branches/SAMBA_4_0/source/pidl 60 pidl cache/history.pidl
./svnlog.pl svn://svnanon.samba.org/samba branches/SAMBA_4_0/source/lib/replace 60 libreplace cache/history.libreplace
./svnlog.pl svn://svnanon.samba.org/samba branches/SOC 60 SOC cache/history.SOC
./svnlog.pl svn://svnanon.samba.org/build-farm trunk 60 build_farm cache/history.build_farm

./cvslog.pl /data/cvs/CVSROOT/rsync.updates 60 rsync "" cache/history.rsync
./cvslog.pl /data/cvs/CVSROOT/distcc.updates 60 distcc "" cache/history.distcc
./cvslog.pl /data/cvs/CVSROOT/ccache.updates 60 ccache "" cache/history.ccache
./cvslog.pl /data/cvs/CVSROOT/ppp.updates 60 ppp "" cache/history.ppp

./bzrlog.pl /home/ftp/pub/unpacked/ctdb 60 cache/history.ctdb
./bzrlog.pl http://people.samba.org/bzr/jelmer/samba-gtk/trunk 60 cache/history.samba-gtk

./gitlog.pl /data/git/samba.git/ 60 v3-2-test cache/history.samba_3_2_test
./gitlog.pl /data/git/samba.git/ 60 v4-0-test cache/history.samba_4_0_test

) > history.log 2>&1
