#!/usr/bin/perl

# Samba.org buildfarm
# Copyright (C) 2008 Andrew Bartlett <abartlet@samba.org>
# Copyright (C) 2008 Jelmer Vernooij <jelmer@samba.org>
#   
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#   
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#   
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

package hostdb;

use DBI;
use warnings;
use strict;

sub new($)
 {
    my ($class, $filename) = @_;
    
    my $dbh = DBI->connect("dbi:SQLite:$filename") or return undef;
    
    my $self = { filename => $filename, dbh => $dbh };
    
    bless($self, $class);
}

sub provision($)
{
	my ($self) = @_;
	
	$self->{dbh}->do("CREATE TABLE host ( name text, owner text, owner_email text, password text, ssh_access int, fqdn text, platform text, permission text );");
	
	$self->{dbh}->do("CREATE UNIQUE INDEX unique_hostname ON host (name);");
}

sub createhost($$$$$$)
{
	my ($self, $name, $platform, $owner, $owner_email, $password, $permission) = @_;
	my $sth = $self->{dbh}->prepare("INSERT INTO host (name, platform, owner, owner_email, password, permission) VALUES (?,?,?,?,?,?)");
	
	$sth->execute($name, $platform, $owner, $owner_email, $password, $permission);
}

sub deletehost($$)
{
	my ($self, $name) = @_;
	
	my $sth = $self->{dbh}->prepare("DELETE FROM host WHERE name = ?");
	
	my $ret = $sth->execute($name);
	
	return ($ret == 1);
}

sub hosts($)
{
	my ($self) = @_;
	
	return $self->{dbh}->selectall_arrayref("SELECT * FROM host", { Slice => {} });
}

sub host($$)
{
	my ($self, $name) = @_;
	
	my $hosts = $self->hosts();
	
	foreach (@$hosts) {
		return $_ if ($_->{name} eq $name);
	}
	
	return undef;
}

sub update_platform($$$)
{
	my ($self, $name, $new_platform) = @_;
	
	my $changed = $self->{dbh}->do("UPDATE host SET platform = ? WHERE name = ?", undef, 
		($new_platform, $name));
	
	return ($changed == 1);
}

sub update_owner($$$$)
{
	my ($self, $name, $new_owner, $new_owner_email) = @_;
	
	my $changed = $self->{dbh}->do("UPDATE host SET owner = ?, owner_email = ? WHERE name = ?", 
				       undef, ($new_owner, $new_owner_email, $name));
	
	return ($changed == 1);
}

# Write out the rsyncd.secrets
sub create_rsync_secrets($)
{
	my ($db) = @_;
	
	my $hosts = $db->hosts();
	
	my $res = "";
	
	$res .= "# rsyncd.secrets file\n";
	$res .= "# automatically generated by textfiles.pl. DO NOT EDIT!\n\n";
	
	foreach (@$hosts) {
		$res .= "# $_->{name}";
		if ($_->{owner}) {
			$res .= ", owner: $_->{owner} <$_->{owner_email}>\n";
		} else {
			$res .= ", owner unknown\n";
		}
		if ($_->{password}) {
			$res .= "$_->{name}:$_->{password}\n\n";
		} else {
			$res .= "# $->{name} password is unknown\n\n";
		}
	}
	
	return $res;
}

# Write out the web/
sub create_hosts_list($)
{
	my ($self) = @_;
	
	my $res = ""; 
	
	my $hosts = $self->hosts();
	
	foreach (@$hosts) {
		$res .= "$_->{name}: $_->{platform}\n";
	}
	
	return $res;
}

1;