#!/usr/bin/perl

# Samba.org buildfarm
# Copyright (C) 2008 Andrew Bartlett <abartlet@samba.org>
# Copyright (C) 2008 Jelmer Vernooij <jelmer@samba.org>
#   
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#   
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#   
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

package hostdb;

use DBI;

sub new($)
 {
    my ($class, $filename) = @_;
    
    my $dbh = DBI->connect("dbi:SQLite:$filename") or return undef;
    
    my $self = { filename => $filename, dbh => $dbh };
    
    bless($self, $class);
}

sub provision($)
{
	my ($self) = @_;
	
	$self->{dbh}->do("CREATE TABLE host ( name text, owner text, owner_email text, password text, ssh_access int, fqdn text, platform text, permission text );");
}

sub createhost($$$$$$)
{
	my ($self, $name, $platform, $owner, $owner_email, $password, $permission) = @_;
	my $sth = $self->{dbh}->prepare("INSERT INTO host (name, platform, owner, owner_email, password, permission) VALUES (?,?,?,?,?,?)");
	
	$sth->execute($name, $platform, $owner, $owner_email, $password, $permission);
}

sub deletehost($$)
{
	my ($self, $name) = @_;
	
	my $sth = $self->{dbh}->prepare("DELETE FROM host WHERE name = ?");
	
	$sth->execute($name);
}

sub hosts($)
{
	my ($self) = @_;
	
	return $self->{dbh}->selectall_arrayref("SELECT * FROM host");
}

# Write out the rsyncd.secrets
sub create_rsync_secrets($$)
{
	my ($db, $filename) = @_;
	
	my $hosts = $db->hosts();
	
	open(OUT, ">$filename") or die("Unable to open $filename: $!");
	
	print OUT "# rsyncd.secrets file\n";
	print OUT "# automatically generated by textfiles.pl. DO NOT EDIT!\n\n";
	
	foreach (values %$hosts) {
		print "# $_->{name}, owner: $_->{owner} <$_->{owner_email}>\n";
		print "$_->{name} $_->{password}\n\n";
	}
	
	close(OUT);
}

# Write out the web/
sub create_hosts_list($$)
{
	my ($self, $filename) = @_;
	
	open(OUT, ">$filename") or die("Unable to open $filename: $!");
	
	my $hosts = $self->hosts();
	
	foreach (values %$hosts) {
		print OUT "$_->{name}: $_->{platform}\n";
	}
	
	close(OUT);
}

1;